apiVersion: apps/v1
kind: Deployment
metadata:
  name: esteban-vue-portfolio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: esteban-vue-portfolio
  template:
    metadata:
      labels:
        app: esteban-vue-portfolio
    spec:
      containers:
      - name: esteban-vue-portfolio
        image: esteban284/esteban-vue-portfolio:latest
        ports:
        - containerPort: 8080